build:
  services:
    - mongo
  tags:
    - go
  script:
    - mkdir -p $GOPATH/src/gitlab.mugsoft.io
    - cp -r ../../vida $GOPATH/src/gitlab.mugsoft.io/
    - cd $GOPATH/src/gitlab.mugsoft.io/vida/go-api
    - go build
    - go test -cover ./...
